### ISSUE TITLE
management command create_relationships not working as expected

### ISSUE THREAD

**Issue by babslgam** [acdh-oeaw/apis-instance-frischmuth#101]
https://github.com/acdh-oeaw/apis-instance-frischmuth/blob/e30dfdd83280d22109a2c157c1ab3c624e728ef2/apis_ontology/models.py#L988-L990

https://github.com/acdh-oeaw/apis-instance-frischmuth/blob/e30dfdd83280d22109a2c157c1ab3c624e728ef2/apis_ontology/models.py#L1041-L1043

**Comment by koeaw** [comment]
@babslgam I can't merge my PR yet because the Ruff errors need fixing first, but for local development at least you can pull in those changes.
