### ISSUE TITLE
add verbose names for the language facet

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-frischmuth#147]
currently the implementation of the language facet does not show the verbose names used in the serialization.

**Comment by koeaw** [comment]
I think this was solved by switching the `TextChoices` values from English values to German labels.

Which was subsequently done for all `TextChoices` relevant to the frontend. I.e. all but [`ProgressStates`](https://github.com/acdh-oeaw/apis-instance-frischmuth/blob/24917fa06f3eb2fc1d50811083a7c76775ffdd4a/apis_ontology/models.py#L21-L28), which is meant for internal use (which we aren't yet using, but could use, to filter out data not yet ready for public consumption, like all "dubios" items.)
