### ISSUE TITLE
App needs redeployment

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-instance-frischmuth#170]
The last deployment [failed](https://github.com/acdh-oeaw/apis-instance-frischmuth/actions/runs/10348777680), I'm assuming this is related to the current partial systems outage on our end.

Making a note of it here, needs :eyes: later.

**Comment by koeaw** [comment]
Deployments are [still failing](https://github.com/acdh-oeaw/apis-instance-frischmuth/actions/runs/10368666151/job/28702865727 )... looks like a Kubernetes problem?

**Comment by b1rger** [comment]
> looks like a Kubernetes problem?

yes, there was a mail yesterday about the infrastructure downtime

**Comment by koeaw** [comment]
> yes, there was a mail yesterday about the infrastructure downtime

Yep, was veering towards this probably (still) being to blame, based on the lack of updates and MM still being down, but wasn't entirely sure. (Also thought the latter may have lower priority either way, so may not be the best indicator.)
