### ISSUE TITLE
fix default settings dependency

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-instance-frischmuth#225]
dependabot chokes when trying to update `apis-acdhch-default-settings`:
```
+----------------------------------------------+
|        Dependencies failed to update         |
+------------------------------+---------------+
| apis-acdhch-default-settings | unknown_error |
+------------------------------+---------------+
```
https://github.com/acdh-oeaw/apis-instance-frischmuth/actions/runs/11473160908/job/31926920005

I guess this is due to the `v` in the version

**Comment by koeaw** [comment]
Thank you, I wasn't even aware of this – should I have got a notification for this? I'm subscribed to all activity on this repo but this doesn't show up anywhere.

Looks like the v was included for previous versions, does this mean this is more of a Dependabot problem but doesn't affect how the dependency is included/pulled from PyPI for the project? Either way, I'll update it.
